//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.head003;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessDataHeaderV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessDataHeaderV01"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Hdr" type="{urn:iso:std:iso:20022:tech:xsd:head.003.001.01}BusinessApplicationHeaderEnvelope"/&gt;
 *         &lt;element name="Pyld" type="{urn:iso:std:iso:20022:tech:xsd:head.003.001.01}StrictPayload"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessDataHeaderV01", propOrder = {
    "hdr",
    "pyld"
})
public class BusinessDataHeaderV01 {

    @XmlElement(name = "Hdr", required = true)
    protected BusinessApplicationHeaderEnvelope hdr;
    @XmlElement(name = "Pyld", required = true)
    protected StrictPayload pyld;

    /**
     * Gets the value of the hdr property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessApplicationHeaderEnvelope }
     *     
     */
    public BusinessApplicationHeaderEnvelope getHdr() {
        return hdr;
    }

    /**
     * Sets the value of the hdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessApplicationHeaderEnvelope }
     *     
     */
    public void setHdr(BusinessApplicationHeaderEnvelope value) {
        this.hdr = value;
    }

    /**
     * Gets the value of the pyld property.
     * 
     * @return
     *     possible object is
     *     {@link StrictPayload }
     *     
     */
    public StrictPayload getPyld() {
        return pyld;
    }

    /**
     * Sets the value of the pyld property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrictPayload }
     *     
     */
    public void setPyld(StrictPayload value) {
        this.pyld = value;
    }

}
