//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.auth072;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SttlmIntlrRpt" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}SettlementInternaliserReportV01"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "sttlmIntlrRpt"
})
public class Document {

    @XmlElement(name = "SttlmIntlrRpt", required = true)
    protected SettlementInternaliserReportV01 sttlmIntlrRpt;

    /**
     * Gets the value of the sttlmIntlrRpt property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementInternaliserReportV01 }
     *     
     */
    public SettlementInternaliserReportV01 getSttlmIntlrRpt() {
        return sttlmIntlrRpt;
    }

    /**
     * Sets the value of the sttlmIntlrRpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementInternaliserReportV01 }
     *     
     */
    public void setSttlmIntlrRpt(SettlementInternaliserReportV01 value) {
        this.sttlmIntlrRpt = value;
    }

}
