//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.auth072;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InternalisationData1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InternalisationData1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Aggt" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData2"/&gt;
 *         &lt;element name="FaildRate" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationDataRate1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternalisationData1", propOrder = {
    "aggt",
    "faildRate"
})
public class InternalisationData1 {

    @XmlElement(name = "Aggt", required = true)
    protected InternalisationData2 aggt;
    @XmlElement(name = "FaildRate", required = true)
    protected InternalisationDataRate1 faildRate;

    /**
     * Gets the value of the aggt property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData2 }
     *     
     */
    public InternalisationData2 getAggt() {
        return aggt;
    }

    /**
     * Sets the value of the aggt property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData2 }
     *     
     */
    public void setAggt(InternalisationData2 value) {
        this.aggt = value;
    }

    /**
     * Gets the value of the faildRate property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationDataRate1 }
     *     
     */
    public InternalisationDataRate1 getFaildRate() {
        return faildRate;
    }

    /**
     * Sets the value of the faildRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationDataRate1 }
     *     
     */
    public void setFaildRate(InternalisationDataRate1 value) {
        this.faildRate = value;
    }

}
