//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.auth072;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InternalisationData2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InternalisationData2"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Sttld" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationDataVolume1"/&gt;
 *         &lt;element name="Faild" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationDataVolume1"/&gt;
 *         &lt;element name="Ttl" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationDataVolume1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternalisationData2", propOrder = {
    "sttld",
    "faild",
    "ttl"
})
public class InternalisationData2 {

    @XmlElement(name = "Sttld", required = true)
    protected InternalisationDataVolume1 sttld;
    @XmlElement(name = "Faild", required = true)
    protected InternalisationDataVolume1 faild;
    @XmlElement(name = "Ttl", required = true)
    protected InternalisationDataVolume1 ttl;

    /**
     * Gets the value of the sttld property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationDataVolume1 }
     *     
     */
    public InternalisationDataVolume1 getSttld() {
        return sttld;
    }

    /**
     * Sets the value of the sttld property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationDataVolume1 }
     *     
     */
    public void setSttld(InternalisationDataVolume1 value) {
        this.sttld = value;
    }

    /**
     * Gets the value of the faild property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationDataVolume1 }
     *     
     */
    public InternalisationDataVolume1 getFaild() {
        return faild;
    }

    /**
     * Sets the value of the faild property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationDataVolume1 }
     *     
     */
    public void setFaild(InternalisationDataVolume1 value) {
        this.faild = value;
    }

    /**
     * Gets the value of the ttl property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationDataVolume1 }
     *     
     */
    public InternalisationDataVolume1 getTtl() {
        return ttl;
    }

    /**
     * Sets the value of the ttl property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationDataVolume1 }
     *     
     */
    public void setTtl(InternalisationDataVolume1 value) {
        this.ttl = value;
    }

}
