//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.auth072;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SettlementInternaliserReportV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementInternaliserReportV01"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RptHdr" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}SettlementInternaliserReportHeader1"/&gt;
 *         &lt;element name="SttlmIntlr" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}SettlementInternaliser1"/&gt;
 *         &lt;element name="IssrCSD" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}IssuerCSDReport1" maxOccurs="unbounded"/&gt;
 *         &lt;element name="SplmtryData" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}SupplementaryData1" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementInternaliserReportV01", propOrder = {
    "rptHdr",
    "sttlmIntlr",
    "issrCSD",
    "splmtryData"
})
public class SettlementInternaliserReportV01 {

    @XmlElement(name = "RptHdr", required = true)
    protected SettlementInternaliserReportHeader1 rptHdr;
    @XmlElement(name = "SttlmIntlr", required = true)
    protected SettlementInternaliser1 sttlmIntlr;
    @XmlElement(name = "IssrCSD", required = true)
    protected List<IssuerCSDReport1> issrCSD;
    @XmlElement(name = "SplmtryData")
    protected List<SupplementaryData1> splmtryData;

    /**
     * Gets the value of the rptHdr property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementInternaliserReportHeader1 }
     *     
     */
    public SettlementInternaliserReportHeader1 getRptHdr() {
        return rptHdr;
    }

    /**
     * Sets the value of the rptHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementInternaliserReportHeader1 }
     *     
     */
    public void setRptHdr(SettlementInternaliserReportHeader1 value) {
        this.rptHdr = value;
    }

    /**
     * Gets the value of the sttlmIntlr property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementInternaliser1 }
     *     
     */
    public SettlementInternaliser1 getSttlmIntlr() {
        return sttlmIntlr;
    }

    /**
     * Sets the value of the sttlmIntlr property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementInternaliser1 }
     *     
     */
    public void setSttlmIntlr(SettlementInternaliser1 value) {
        this.sttlmIntlr = value;
    }

    /**
     * Gets the value of the issrCSD property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the issrCSD property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIssrCSD().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IssuerCSDReport1 }
     * 
     * 
     */
    public List<IssuerCSDReport1> getIssrCSD() {
        if (issrCSD == null) {
            issrCSD = new ArrayList<IssuerCSDReport1>();
        }
        return this.issrCSD;
    }

    /**
     * Gets the value of the splmtryData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the splmtryData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSplmtryData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupplementaryData1 }
     * 
     * 
     */
    public List<SupplementaryData1> getSplmtryData() {
        if (splmtryData == null) {
            splmtryData = new ArrayList<SupplementaryData1>();
        }
        return this.splmtryData;
    }

}
