//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.auth072;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SettlementInternaliserTransactionType1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementInternaliserTransactionType1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SctiesBuyOrSell" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="CollMgmtOpr" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="SctiesLndgOrBrrwg" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="RpAgrmt" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="OthrTxs" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementInternaliserTransactionType1", propOrder = {
    "sctiesBuyOrSell",
    "collMgmtOpr",
    "sctiesLndgOrBrrwg",
    "rpAgrmt",
    "othrTxs"
})
public class SettlementInternaliserTransactionType1 {

    @XmlElement(name = "SctiesBuyOrSell", required = true)
    protected InternalisationData1 sctiesBuyOrSell;
    @XmlElement(name = "CollMgmtOpr", required = true)
    protected InternalisationData1 collMgmtOpr;
    @XmlElement(name = "SctiesLndgOrBrrwg", required = true)
    protected InternalisationData1 sctiesLndgOrBrrwg;
    @XmlElement(name = "RpAgrmt", required = true)
    protected InternalisationData1 rpAgrmt;
    @XmlElement(name = "OthrTxs", required = true)
    protected InternalisationData1 othrTxs;

    /**
     * Gets the value of the sctiesBuyOrSell property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getSctiesBuyOrSell() {
        return sctiesBuyOrSell;
    }

    /**
     * Sets the value of the sctiesBuyOrSell property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setSctiesBuyOrSell(InternalisationData1 value) {
        this.sctiesBuyOrSell = value;
    }

    /**
     * Gets the value of the collMgmtOpr property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getCollMgmtOpr() {
        return collMgmtOpr;
    }

    /**
     * Sets the value of the collMgmtOpr property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setCollMgmtOpr(InternalisationData1 value) {
        this.collMgmtOpr = value;
    }

    /**
     * Gets the value of the sctiesLndgOrBrrwg property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getSctiesLndgOrBrrwg() {
        return sctiesLndgOrBrrwg;
    }

    /**
     * Sets the value of the sctiesLndgOrBrrwg property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setSctiesLndgOrBrrwg(InternalisationData1 value) {
        this.sctiesLndgOrBrrwg = value;
    }

    /**
     * Gets the value of the rpAgrmt property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getRpAgrmt() {
        return rpAgrmt;
    }

    /**
     * Sets the value of the rpAgrmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setRpAgrmt(InternalisationData1 value) {
        this.rpAgrmt = value;
    }

    /**
     * Gets the value of the othrTxs property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getOthrTxs() {
        return othrTxs;
    }

    /**
     * Sets the value of the othrTxs property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setOthrTxs(InternalisationData1 value) {
        this.othrTxs = value;
    }

}
