//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.15 at 01:34:27 PM CEST 
//


package li.bankfrick.informatik.reporting.csdr.xml.entities.auth072;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SettlementInternaliserFinancialInstrument1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementInternaliserFinancialInstrument1"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Eqty" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="SvrgnDebt" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="Bd" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="OthrTrfblScties" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="XchgTradgFnds" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="CllctvInvstmtUdrtkgs" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="MnyMktInstrm" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="EmssnAllwnc" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *         &lt;element name="OthrFinInstrms" type="{urn:iso:std:iso:20022:tech:xsd:auth.072.001.01}InternalisationData1"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementInternaliserFinancialInstrument1", propOrder = {
    "eqty",
    "svrgnDebt",
    "bd",
    "othrTrfblScties",
    "xchgTradgFnds",
    "cllctvInvstmtUdrtkgs",
    "mnyMktInstrm",
    "emssnAllwnc",
    "othrFinInstrms"
})
public class SettlementInternaliserFinancialInstrument1 {

    @XmlElement(name = "Eqty", required = true)
    protected InternalisationData1 eqty;
    @XmlElement(name = "SvrgnDebt", required = true)
    protected InternalisationData1 svrgnDebt;
    @XmlElement(name = "Bd", required = true)
    protected InternalisationData1 bd;
    @XmlElement(name = "OthrTrfblScties", required = true)
    protected InternalisationData1 othrTrfblScties;
    @XmlElement(name = "XchgTradgFnds", required = true)
    protected InternalisationData1 xchgTradgFnds;
    @XmlElement(name = "CllctvInvstmtUdrtkgs", required = true)
    protected InternalisationData1 cllctvInvstmtUdrtkgs;
    @XmlElement(name = "MnyMktInstrm", required = true)
    protected InternalisationData1 mnyMktInstrm;
    @XmlElement(name = "EmssnAllwnc", required = true)
    protected InternalisationData1 emssnAllwnc;
    @XmlElement(name = "OthrFinInstrms", required = true)
    protected InternalisationData1 othrFinInstrms;

    /**
     * Gets the value of the eqty property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getEqty() {
        return eqty;
    }

    /**
     * Sets the value of the eqty property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setEqty(InternalisationData1 value) {
        this.eqty = value;
    }

    /**
     * Gets the value of the svrgnDebt property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getSvrgnDebt() {
        return svrgnDebt;
    }

    /**
     * Sets the value of the svrgnDebt property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setSvrgnDebt(InternalisationData1 value) {
        this.svrgnDebt = value;
    }

    /**
     * Gets the value of the bd property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getBd() {
        return bd;
    }

    /**
     * Sets the value of the bd property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setBd(InternalisationData1 value) {
        this.bd = value;
    }

    /**
     * Gets the value of the othrTrfblScties property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getOthrTrfblScties() {
        return othrTrfblScties;
    }

    /**
     * Sets the value of the othrTrfblScties property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setOthrTrfblScties(InternalisationData1 value) {
        this.othrTrfblScties = value;
    }

    /**
     * Gets the value of the xchgTradgFnds property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getXchgTradgFnds() {
        return xchgTradgFnds;
    }

    /**
     * Sets the value of the xchgTradgFnds property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setXchgTradgFnds(InternalisationData1 value) {
        this.xchgTradgFnds = value;
    }

    /**
     * Gets the value of the cllctvInvstmtUdrtkgs property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getCllctvInvstmtUdrtkgs() {
        return cllctvInvstmtUdrtkgs;
    }

    /**
     * Sets the value of the cllctvInvstmtUdrtkgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setCllctvInvstmtUdrtkgs(InternalisationData1 value) {
        this.cllctvInvstmtUdrtkgs = value;
    }

    /**
     * Gets the value of the mnyMktInstrm property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getMnyMktInstrm() {
        return mnyMktInstrm;
    }

    /**
     * Sets the value of the mnyMktInstrm property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setMnyMktInstrm(InternalisationData1 value) {
        this.mnyMktInstrm = value;
    }

    /**
     * Gets the value of the emssnAllwnc property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getEmssnAllwnc() {
        return emssnAllwnc;
    }

    /**
     * Sets the value of the emssnAllwnc property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setEmssnAllwnc(InternalisationData1 value) {
        this.emssnAllwnc = value;
    }

    /**
     * Gets the value of the othrFinInstrms property.
     * 
     * @return
     *     possible object is
     *     {@link InternalisationData1 }
     *     
     */
    public InternalisationData1 getOthrFinInstrms() {
        return othrFinInstrms;
    }

    /**
     * Sets the value of the othrFinInstrms property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalisationData1 }
     *     
     */
    public void setOthrFinInstrms(InternalisationData1 value) {
        this.othrFinInstrms = value;
    }

}
